# Generated by Django 4.2.11 on 2026-05-06 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mood', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moodlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='moodlog',
            constraint=models.UniqueConstraint(fields=('user', 'log_date'), name='unique_user_mood_per_day'),
        ),
    ]
