# Generated by Django 4.2.11 on 2026-05-06 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PHYSICAL', 'Fisik'), ('MENTAL', 'Mental'), ('SLEEP', 'Tidur'), ('NUTRITION', 'Nutrisi'), ('MINDFULNESS', 'Mindfulness'), ('DIGITAL', 'Digital Detox')], max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Mudah'), ('MEDIUM', 'Sedang'), ('HARD', 'Sulit')], default='EASY', max_length=10)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('icon', models.CharField(default='star', help_text='Lucide icon name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'xp_reward'],
            },
        ),
        migrations.CreateModel(
            name='UserQuestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(default=django.utils.timezone.localdate)),
                ('xp_earned', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='quests.quest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
